config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD

  devise_for :admins, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }

=======
>>>>>>> 8affcfd854fc6bc220b8b745150afb732a40f124
  namespace :admin do
    resources :order_details, only:[:update]
    resources :orders, only:[:index,:show,:update]
    resources :genres, only:[:index,:create,:edit,:update]
    resources :products, only:[:index,:new,:create,:show,:edit,:update]
    resources :customers, only:[:index,:show,:edit,:update]
<<<<<<< HEAD
    root :to => "homes#top"

  end

  devise_for :customers, controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }

  scope module: :public do

   resources :products, only:[:index,:show,]
   resources :shippings, only:[:index,:create,:edit,:update,:destroy]
   resource :customers, only:[:show,:update]
   get 'customer_edit' => 'customers#edit', as: 'customer_edit'
   patch 'customers/update' => 'customers#update'
   get 'customers/unsubscribe'
   patch 'customers/withdraw'
=======
  end

  namespace :public do
   resources :shippings, only:[:index,:create,:edit,:update]
   resource :users, only:[:show,:edit,:update]
   get 'users/unsubscribe'
   patch 'users/withdraw'
   resources :orders, only:[:new,:create,:index,:show]
>>>>>>> 8affcfd854fc6bc220b8b745150afb732a40f124
   get 'orders/thankyou'
   resources :orders, only:[:new,:create,:index,:show]
   post 'orders/comfirm'
<<<<<<< HEAD
   delete 'cart_products/destroy_all'
   resources :cart_products, only:[:create,:index,:update,:destroy]
=======
   resources :cart_products, only:[:new,:create,:index,:show]
>>>>>>> 8affcfd854fc6bc220b8b745150afb732a40f124
   root :to => "homes#top"
   get 'homes/about'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
    belongs_to :customer
    belongs_to :product

  def sum_of_price
    product.add_tax_price * quantity
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_products
  has_many :orders
  has_many :shippings
  
  def full_name
    self.last_name + self.first_name
  end

  def active_for_authentication?
    super && (self.delete_user == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_details, dependent: :destroy
    enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
    enum order_status: { 入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済:4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :product

  def sum_of_price
    product.add_tax_price * quantity
  end

  enum production_status: { 着手不可:0, 製作待ち:1, 製作中:2, 製作完了:3 }

end

app/models/product.rb
class Product < ApplicationRecord
    has_many :cart_products
    has_many :order_details
    belongs_to :genre
<<<<<<< HEAD
    attachment :image

    def  add_tax_price
        (self.price * 1.10).round
    end
=======
>>>>>>> 8affcfd854fc6bc220b8b745150afb732a40f124
end

app/models/public.rb
module Public
  def self.table_name_prefix
    'public_'
  end
end

app/models/shipping.rb
class Shipping < ApplicationRecord
  belongs_to :customer
  def shipping_address
    self.postcode + self.address + self.name
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  def index
     @customers = Customer.all
     @customers = Customer.page(params[:id])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customers = Customer.find(params[:id])
    customers.update(customer_params)
    flash[:notice] = "会員情報を変更しました。"
    redirect_to admin_customers_path
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number, :password, :delete_user)
  end
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    if params[:check] == "0"
      @orders = Order.all.page(params[:page]).per(10)
    elsif params[:check] && (params[:check] != "0")
      @orders = Order.where(customer_id: params[:check]).page(params[:page]).per(8)
      @notice = "注文履歴のみ表示しています。全ての会員の履歴はページ上部のリンクからご覧ください。"
    else
      @orders = Order.all.page(params[:page]).per(8)
    end
  end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    if params[:check] == "0"
      @orders = Order.all.page(params[:page]).per(10)
    elsif params[:check] && (params[:check] != "0")
      @orders = Order.where(customer_id: params[:check]).page(params[:page]).per(8)
      @notice = "注文履歴のみ表示しています。全ての会員の履歴はページ上部のリンクからご覧ください。"
    else
      @orders = Order.all.page(params[:page]).per(8)
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.order_status == "入金確認"
       @order.order_details.each do |order_detail|
         order_detail.update(production_status: "製作待ち")
       end
    end
      redirect_back(fallback_location: root_path)
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery with: :exception
<<<<<<< HEAD
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number])
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_requied
    redirect_to login_path unless current_user
  end

end
=======
end
>>>>>>> 8affcfd854fc6bc220b8b745150afb732a40f124

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/order_detailes_helper.rb
module Admin::OrderDetailesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-9 col-xl-8 mx-auto">
      <div class="col-md-5 text-center mx-auto mb-3">
        <h2 class="mb-4"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報</h2>
      </div>
      <%= form_with model: @customer, url: admin_customer_path, local: true, class: "mb-3 pl-md-3" do |f| %>
      
      <div class="form-group">
        <%= f.label :会員id %>
        <%= f.label :"#{@customer.id}" %>
      </div>
      
      <div class="form-group row">
        <%= f.label "氏名", class: "col-md-4 col-form-label" %>
        <div class="col-sm-6 col-md-4">
          <%= f.text_field :last_name, autofocus: true,  placeholder: "", class:"form-control" %>
        </div>
        <div class="col-sm-6 col-md-4">
          <%= f.text_field :first_name, autofocus: true,  placeholder: "", class:"form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :last_name_kana, "フリガナ", class: "col-md-4 col-form-label" %>
        <div class="col-sm-6 col-md-4">
          <%= f.text_field :last_name_kana, autofocus: true,  placeholder: "", class:"form-control" %>
        </div>
        <div class="col-sm-6 col-md-4">
          <%= f.text_field :first_name_kana, autofocus: true,  placeholder: "", class:"form-control" %>
        </div>
      </div>
      
      <div class="form-group row">
        <%= f.label :postcode, "郵便番号", class: "col-md-4 col-form-label" %>
        <div class="col-sm-6 col-md-4">
          <%= f.text_field :postcode, autofocus: true, placeholder: "", class:"form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :addres, "住所", class: "col-md-4 col-form-label" %>
        <div class="col-md-8">
          <%= f.text_area :address, autofocus: true, placeholder: "", class:"form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :phone_number, "電話番号", class: "col-md-4 col-form-label" %>
        <div class="col-sm-6 col-md-4">
          <%= f.text_field :phone_number, autofocus: true, placeholder: "", class:"form-control" %>
        </div>
      </div>
      
      <div class="form-group row">
        <%= f.label :email, "メールアドレス", class: "col-md-4 col-form-label" %>
        <div class="col-sm-6 col-md-4">
          <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "", class:"form-control" %>
        </div>
      </div>
        
      <div class="form-group row">
        <%= f.label :delete_user, "会員ステータス", class: "col-md-4 col-form-label" %>
        <%= f.radio_button :delete_user, false %>
        <%= f.label :user_status, "有効" %>
        <%= f.radio_button :delete_user, true %>
      　<%= f.label :user_status, "退会" %>
      <div class="col-sm-6 col-md-4"></div>
      <div class="form-group row">
        <div class="col-7 text-right">
          <%= f.submit "変更を保存する", class:"btn btn-success" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row m-5">
    <h4 class="font-weight-normal">会員一覧</h4>

    <table class="table table-hover table-invers">
      <thead>
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td class="align-middle"><%= customer.id %></td>
          <td class="align-middle"><u><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id), class:"font-weight-bold" %></u></td>
          <td class="align-middle"><%= customer.email %></td>
          <td class="align-middle">
            <% if customer.delete_user == false %>
              <p class="text-success font-weight-bold">有効</p>
            <% else %>
              <p class="text-secondary">退会</p>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    
    <%= paginate @customers %>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  
  <div class="row my-3">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h2><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h2>
    </div>
  </div>
  
  <div class="row">
    <div class="col-sm-6 px-sm-0 offset-sm-1">
      <table class="table table-bordered">
        <tr>
          <th class="table-active">会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th class="table-active">氏名</th>
          <td><%= @customer.last_name + @customer.first_name %></td>
        </tr>
        <tr>
          <th class="table-active">フリガナ</th>
          <td><%= @customer.last_name_kana + @customer.first_name_kana %></td>
        </tr>
        <tr>
          <th class="table-active">郵便番号</th>
          <td><%= @customer.postcode %></td>
        </tr>
        <tr>
          <th class="table-active">住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th class="table-active">電話番号</th>
          <td><%= @customer.phone_number %></td>
        </tr>
        <tr>
          <th class="table-active">メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th class="table-active">会員ステータス</th>
            <% if @customer.delete_user == false %>
              <td class="text-success font-weight-bold">有効</td>
            <% else %>
              <td class="text-secondary">退会<td>
            <% end %>
        </tr>
      </table>
    </div>
  </div>
  
  <div class="row mb-2">
    <div class="col-lg-6 px-sm-0 offset-sm-1">
      <%= link_to "編集する", edit_admin_customer_path(@customer.id), class:"btn btn-success my-1 mx-4 px-4" %>
      <%= link_to "注文履歴一覧を見る", admin_orders_path, class:"btn btn-primary mx-4 px-4" %>
      <%#= link_to "注文履歴一覧を見る", admin_path(id: @customer), class:"btn btn-primary mx-4 px-4" %>
    </div>
  </div>

</div>