config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD

  devise_for :admins, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }

=======
>>>>>>> 8affcfd854fc6bc220b8b745150afb732a40f124
  namespace :admin do
    resources :order_details, only:[:update]
    resources :orders, only:[:index,:show,:update]
    resources :genres, only:[:index,:create,:edit,:update]
    resources :products, only:[:index,:new,:create,:show,:edit,:update]
    resources :customers, only:[:index,:show,:edit,:update]
<<<<<<< HEAD
    root :to => "homes#top"

  end

  devise_for :customers, controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }

  scope module: :public do

   resources :products, only:[:index,:show,]
   resources :shippings, only:[:index,:create,:edit,:update,:destroy]
   resource :customers, only:[:show,:update]
   get 'customer_edit' => 'customers#edit', as: 'customer_edit'
   patch 'customers/update' => 'customers#update'
   get 'customers/unsubscribe'
   patch 'customers/withdraw'
=======
  end

  namespace :public do
   resources :shippings, only:[:index,:create,:edit,:update]
   resource :users, only:[:show,:edit,:update]
   get 'users/unsubscribe'
   patch 'users/withdraw'
   resources :orders, only:[:new,:create,:index,:show]
>>>>>>> 8affcfd854fc6bc220b8b745150afb732a40f124
   get 'orders/thankyou'
   resources :orders, only:[:new,:create,:index,:show]
   post 'orders/comfirm'
<<<<<<< HEAD
   delete 'cart_products/destroy_all'
   resources :cart_products, only:[:create,:index,:update,:destroy]
=======
   resources :cart_products, only:[:new,:create,:index,:show]
>>>>>>> 8affcfd854fc6bc220b8b745150afb732a40f124
   root :to => "homes#top"
   get 'homes/about'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
    belongs_to :customer
    belongs_to :product

  def sum_of_price
    product.add_tax_price * quantity
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_products
  has_many :orders
  has_many :shippings
  
  def full_name
    self.last_name + self.first_name
  end

  def active_for_authentication?
    super && (self.delete_user == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_details, dependent: :destroy
    enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
    enum order_status: { 入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済:4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :product

  def sum_of_price
    product.add_tax_price * quantity
  end

  enum production_status: { 着手不可:0, 製作待ち:1, 製作中:2, 製作完了:3 }

end

app/models/product.rb
class Product < ApplicationRecord
    has_many :cart_products
    has_many :order_details
    belongs_to :genre
<<<<<<< HEAD
    attachment :image

    def  add_tax_price
        (self.price * 1.10).round
    end
=======
>>>>>>> 8affcfd854fc6bc220b8b745150afb732a40f124
end

app/models/public.rb
module Public
  def self.table_name_prefix
    'public_'
  end
end

app/models/shipping.rb
class Shipping < ApplicationRecord
  belongs_to :customer
  def shipping_address
    self.postcode + self.address + self.name
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    if params[:check] == "0"
      @orders = Order.all.page(params[:page]).per(10)
    elsif params[:check] && (params[:check] != "0")
      @orders = Order.where(customer_id: params[:check]).page(params[:page]).per(8)
      @notice = "注文履歴のみ表示しています。全ての会員の履歴はページ上部のリンクからご覧ください。"
    else
      @orders = Order.all.page(params[:page]).per(8)
    end
  end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    if params[:check] == "0"
      @orders = Order.all.page(params[:page]).per(10)
    elsif params[:check] && (params[:check] != "0")
      @orders = Order.where(customer_id: params[:check]).page(params[:page]).per(8)
      @notice = "注文履歴のみ表示しています。全ての会員の履歴はページ上部のリンクからご覧ください。"
    else
      @orders = Order.all.page(params[:page]).per(8)
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.order_status == "入金確認"
       @order.order_details.each do |order_detail|
         order_detail.update(production_status: "製作待ち")
       end
    end
      redirect_back(fallback_location: root_path)
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  
  def index
<<<<<<< HEAD
    @products = Product.all.page(params[:page]).per(10)
=======
>>>>>>> 8affcfd854fc6bc220b8b745150afb732a40f124
  end

  def new
  end

  def create
<<<<<<< HEAD
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path
    else
      render :new
    end
=======
>>>>>>> 8affcfd854fc6bc220b8b745150afb732a40f124
  end

  def show
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    product = Product.find(params[:id])
    product.update(product_params)
    redirect_to admin_product_path(product)
  end
<<<<<<< HEAD
  
  private

  def product_params
    params.require(:product).permit(:name, :image, :description, :price, :genre_id, :is_active)
  end
  
=======
>>>>>>> 8affcfd854fc6bc220b8b745150afb732a40f124
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery with: :exception
<<<<<<< HEAD
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number])
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_requied
    redirect_to login_path unless current_user
  end

end
=======
end
>>>>>>> 8affcfd854fc6bc220b8b745150afb732a40f124

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/order_detailes_helper.rb
module Admin::OrderDetailesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">

  <div class="row m-5">
    <div class="row">
      <h4>ジャンル編集</h4>
    </div>
  </div>

  <div class="row m-5 form-group">
    <%= form_with model: @genre , url: admin_genre_path, data: {"turbolinks"=>false}, local: true do |f| %>
    <%= f.label "ジャンル名" %>
    <%= f.text_field :name %>
    <%= f.submit '変更を保存', class:"btn btn-success", data: {"turbolinks"=>false} %>
    <% end %>
  </div>

</div>

app/views/admin/genres/index.html.erb
<div class="container px-5 px-sm-0">

  <div class="row m-5">
    <h4>ジャンル追加・一覧</h4>
  </div>

  <div class="row-5 mt-5 mb-5">
    <div class="col-7">
      <%= form_with model: @genre, url: admin_genres_path, local:true do |f|%>
      <%= f.label "ジャンル名", class: "col-md-4 col-form-label" %>
      <%= f.text_field :name ,placeholder: "ジャンル名" %>
      <%= f.submit '新規登録', class:"btn btn-success"%>
      <% end %>
    </div>
    <div class="col-5"></div>
  </div>

  <div class="row ml-2">
    <div class="col-5">
      <table  class="table table-hover table-invers">
        <thead>
          <tr>
            <th>ジャンル</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <% @genres.each do |genre| %>
            <td><%= genre.name %></td>
            <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class:"btn btn-success" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-7"></div>
  </div>

</div>

app/views/admin/orders/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row m-5">
    <h2 class="font-weight-normal">注文履歴一覧</h2>

    <table class="table table-hover table-invers">
      <thead>
        <tr>
          <th>購入日時</th>
          <th>購入者</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
        <tr>
          <td><%= link_to order.created_at.strftime('%Y/%m/%d %H:%M:%S'), admin_order_path(order.id) %></td>
          <td><%= order.customer.full_name %></td>
          <td><%= order.order_details.sum(:quantity) %></td>
          <td><%= order.order_status %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="row m-4">
    <div class="mx-auto"><%= paginate @orders %></div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-9">
      <h2 class="mb-3">注文履歴詳細</h2>
      <table class="table table-borderless">
        <tr>
          <th>購入者</th>
          <td>
            <%= link_to admin_customer_path(@order.customer) do %>
              <%= @order.customer.last_name + " " + @order.customer.first_name %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>
            <%= "〒#{@order.postcode} #{@order.address}" %><br>
            <%= @order.address_name %>
          </td>
        </tr>
        <tr>
          <th>支払い方法</th>
          <td><%= @order.payment_method %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <%= form_with model: [:admin, @order], local:true, class: "form-inline" do |f| %>
              <%= f.select :order_status, @order.class.order_statuses.keys,  {}, {class: "custom-select mb-2 mr-sm-2"} %>
              <%= f.submit "更新", class: "btn btn-success mb-2" %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>

  <div class="row align-items-end">
    <div class="col-lg-9">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>商品名</th>
            <th class="text-right">単価(税込)</th>
            <th class="text-right">数量</th>
            <th class="text-right">小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |order_detail| %>
            <tr>
              <td><%= order_detail.product.name %></td>
              <td class="text-right"><%= order_detail.taxed_price.to_s(:delimited) %></td>
              <td class="text-right"><%= order_detail.quantity.to_s(:delimited) %></td>
              <td class="text-right"><%= (order_detail.taxed_price * order_detail.quantity).to_s(:delimited) %></td>
              <td>
                <%= form_with model: [:admin, order_detail], local:true, class: "form-inline" do |f| %>
                  <%= f.select :production_status, order_detail.class.production_statuses.keys,  {}, {class: "custom-select mb-2 mr-sm-2"} %>
                  <%= f.submit "更新", class: "btn btn-success mb-2" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="ml-auto col-sm-6 col-lg-3">
      <table class="table table-borderless">
        <tr>
          <th>商品合計</th>
          <td class="text-right"><%= @order.total_price.to_s(:delimited) %> 円</td>
        </tr>
        <tr>
          <th>送料</th>
          <td class="text-right"><%= @order.shipping_fee.to_s(:delimited) %> 円</td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td class="text-right"><%= (@order.total_price + @order.shipping_fee).to_s(:delimited) %> 円</td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/admin/products/edit.html.erb
<div class="container">
  
  <div class="row m-5">
    <div class="col-md-10 col-lg-9 col-xl-8 mx-auto">
      <div class="row mb-5 p-2">
        <h3>商品編集</h3>
      </div>
        
      <%= form_with model: @product, url: admin_product_path, local: true do |f| %>
      
      <div class="form-group row">
        <%= f.label "商品画像", class: "col-md-4 col-form-label" %>
          <div class="col-md-4">
            <%= f.attachment_field :image, placeholder: "ファイルを選択" %>
          </div>
      </div>
      
      <div class="form-group row">
        <%= f.label "商品名", class: "col-md-4 col-form-label" %>
          <div class="col-md-4">
            <%= f.text_field :name ,placeholder: "商品名", :size=>"40" %>
          </div>
      </div>
      
      <div class="form-group row">
        <%= f.label "商品説明", class: "col-md-4 col-form-label" %>
          <div class="col-md-4">
            <%= f.text_area :description ,placeholder: "ここに説明文を記述します", :size=>"39x6" %>
          </div>
      </div>
      
      <div class="form-group row">
        <%= f.label "ジャンル", class: "col-md-4 col-form-label" %>
          <div class="col-md-4">
            <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択して下さい--" %>
          </div>
      </div>
      
      <div class="form-group row d-flex flex-row">
        <%= f.label "税抜価格", class: "col-md-4 col-form-label" %>
          <div class="col-md-6">
            <%= f.text_field :price ,placeholder: "1000", :size=>"40" %>
          </div>
          <label class="col-md-2">円</label>
      </div>
      
      <div class="form-group row">
        <%= f.label "販売ステータス", class: "col-md-4 col-form-label" %>
          <div class="col-md-4">
            <%= f.radio_button :is_active, :true, checked: true %>
            <%= f.label :is_active, "販売中", {value: :true, style: "display: inline-block;"} %>
            <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, "販売停止中", {value: :false, style: "display: inline-block;"} %>
          </div>
      </div>
      
      <div class="form-group row mt-5">
          <div class="col-4 offset-md-4">
            <%= f.submit '変更を保存', class:"btn btn-success" %>
          </div>
      </div>
      
      <% end %>
        
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row m-5">
    <div class="col-2">
      <h2 class="font-weight-normal">商品一覧</h2>
    </div>
      <div class="col-8"></div>
      <div class="col-2">
        <%= link_to "新規追加", new_admin_product_path, class: "btn btn-success" %>
      </div>
        <table class="table table-hover table-invers">
      <thead>
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
        <tr>
          <td><%= product.id %></td>
          <td><%= link_to product.name, "/admin/products/#{product.id}" %></td>
          <td><%= product.price %>円</td>
          <td><%= product.genre.name %></td>
          <td>
            <% if product.is_active == true %>
              <font color="green">販売中</font>
            <% else %>
            <font color="#C0C0C0">販売停止中</font>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="row m-4">
    <div class="mx-auto"><%= paginate @products %></div>
  </div>

</div>

app/views/admin/products/new.html.erb
<<<<<<< HEAD
<div class="container">
  
  <div class="row m-5">
    <div class="col-md-10 col-lg-9 col-xl-8 mx-auto">
      <div class="row mb-5 p-2">
        <h3>商品新規登録</h3>
      </div>
        
      <%= form_with model: @product, url: admin_products_path, local: true do |f| %>
      
      <div class="form-group row">
        <%= f.label "商品画像", class: "col-md-4 col-form-label" %>
          <div class="col-md-4">
            <%= f.attachment_field :image, placeholder: "ファイルを選択" %>
          </div>
      </div>
      
      <div class="form-group row">
        <%= f.label "商品名", class: "col-md-4 col-form-label" %>
          <div class="col-md-4">
            <%= f.text_field :name ,placeholder: "商品名", :size=>"40" %>
          </div>
      </div>
      
      <div class="form-group row">
        <%= f.label "商品説明", class: "col-md-4 col-form-label" %>
          <div class="col-md-4">
            <%= f.text_area :description ,placeholder: "ここに説明文を記述します", :size=>"39x6" %>
          </div>
      </div>
      
      <div class="form-group row">
        <%= f.label "ジャンル", class: "col-md-4 col-form-label" %>
          <div class="col-md-4">
            <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択して下さい--" %>
          </div>
      </div>
      
      <div class="form-group row d-flex flex-row">
        <%= f.label "税抜価格", class: "col-md-4 col-form-label" %>
          <div class="col-md-6">
            <%= f.text_field :price ,placeholder: "1000", :size=>"40" %>
          </div>
          <label class="col-md-2">円</label>
      </div>
      
      <div class="form-group row">
        <%= f.label "販売ステータス", class: "col-md-4 col-form-label" %>
          <div class="col-md-4">
            <%= f.radio_button :is_active, :true, checked: true %>
            <%= f.label :is_active, "販売中", {value: :true, style: "display: inline-block;"} %>
            <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, "販売停止中", {value: :false, style: "display: inline-block;"} %>
          </div>
      </div>
      
      <div class="form-group row mt-5">
          <div class="col-7 text-right">
            <%= f.submit '新規登録', class:"btn btn-success" %>
          </div>
      </div>
      
      <% end %>
        
    </div>
  </div>
</div>
=======
<h1>Admin::Products#new</h1>
<p>Find me in app/views/admin/products/new.html.erb</p>
>>>>>>> 8affcfd854fc6bc220b8b745150afb732a40f124

app/views/admin/products/show.html.erb
<<<<<<< HEAD
<div class="container px-5 px-sm-0">
  <div class="row m-5">
      <h3>商品詳細</h3>
　</div>
  <div class="row m-5 p-5">

    <div class="col-md-5">
      <%= attachment_image_tag @product, :image, format: 'jpeg', size: "300x220" %>
    </div>
    
    <div class="col-md-7">
      
      <table>
        <thead>
          <tr>
            <td style="width: 40%">商品名</td>
            <td style="width: 5%"></td>
            <td style="width: 55%"><%= @product.name %></td>
          <tr>
            
            <td>商品説明</td>
            <td></td>
            <td><%= @product.description %></td>
          </tr>
          
          <tr>
            <td>ジャンル</td>
            <td></td>
            <td><%= @product.genre.name %></td>
          </tr>
          
          <tr>
            <td>税込価格<br>(税抜価格)</td>
            <td></td>
            <td><%= @product.add_tax_price.to_s(:taxed_price) %>円(<%= @product.price%>円)</td>
          </tr>
          
          <tr>
            <td>販売ステータス</td>
            <td></td>
            <td>
              <% if @product.is_active == true %>
              　<font color="green">販売中</font>
              <% else %>
                <font color="#C0C0C0">販売停止中</font>
              <% end %>
            </td>
          </tr>
        </thead>
      </table>
      

      <div class="row">
        <div class="ml-5 mt-5">
          <%= link_to "編集する", edit_admin_product_path(@product) ,class:'btn btn-success' %>
        </div>
      </div>
      
      
    </div>

  </div>
</div>
  
=======
<h1>Admin::Products#show</h1>
<p>Find me in app/views/admin/products/show.html.erb</p>
>>>>>>> 8affcfd854fc6bc220b8b745150afb732a40f124