config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD

  devise_for :admins, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }

=======
>>>>>>> 8affcfd854fc6bc220b8b745150afb732a40f124
  namespace :admin do
    resources :order_details, only:[:update]
    resources :orders, only:[:index,:show,:update]
    resources :genres, only:[:index,:create,:edit,:update]
    resources :products, only:[:index,:new,:create,:show,:edit,:update]
    resources :customers, only:[:index,:show,:edit,:update]
<<<<<<< HEAD
    root :to => "homes#top"

  end

  devise_for :customers, controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }

  scope module: :public do

   resources :products, only:[:index,:show,]
   resources :shippings, only:[:index,:create,:edit,:update,:destroy]
   resource :customers, only:[:show,:update]
   get 'customer_edit' => 'customers#edit', as: 'customer_edit'
   patch 'customers/update' => 'customers#update'
   get 'customers/unsubscribe'
   patch 'customers/withdraw'
=======
  end

  namespace :public do
   resources :shippings, only:[:index,:create,:edit,:update]
   resource :users, only:[:show,:edit,:update]
   get 'users/unsubscribe'
   patch 'users/withdraw'
   resources :orders, only:[:new,:create,:index,:show]
>>>>>>> 8affcfd854fc6bc220b8b745150afb732a40f124
   get 'orders/thankyou'
   resources :orders, only:[:new,:create,:index,:show]
   post 'orders/comfirm'
<<<<<<< HEAD
   delete 'cart_products/destroy_all'
   resources :cart_products, only:[:create,:index,:update,:destroy]
=======
   resources :cart_products, only:[:new,:create,:index,:show]
>>>>>>> 8affcfd854fc6bc220b8b745150afb732a40f124
   root :to => "homes#top"
   get 'homes/about'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
    belongs_to :customer
    belongs_to :product

  def sum_of_price
    product.add_tax_price * quantity
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_products
  has_many :orders
  has_many :shippings
  
  def full_name
    self.last_name + self.first_name
  end

  def active_for_authentication?
    super && (self.delete_user == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_details, dependent: :destroy
    enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
    enum order_status: { 入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済:4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :product

  def sum_of_price
    product.add_tax_price * quantity
  end

  enum production_status: { 着手不可:0, 製作待ち:1, 製作中:2, 製作完了:3 }

end

app/models/product.rb
class Product < ApplicationRecord
    has_many :cart_products
    has_many :order_details
    belongs_to :genre
<<<<<<< HEAD
    attachment :image

    def  add_tax_price
        (self.price * 1.10).round
    end
=======
>>>>>>> 8affcfd854fc6bc220b8b745150afb732a40f124
end

app/models/public.rb
module Public
  def self.table_name_prefix
    'public_'
  end
end

app/models/shipping.rb
class Shipping < ApplicationRecord
  belongs_to :customer
  def shipping_address
    self.postcode + self.address + self.name
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    if params[:check] == "0"
      @orders = Order.all.page(params[:page]).per(10)
    elsif params[:check] && (params[:check] != "0")
      @orders = Order.where(customer_id: params[:check]).page(params[:page]).per(8)
      @notice = "注文履歴のみ表示しています。全ての会員の履歴はページ上部のリンクからご覧ください。"
    else
      @orders = Order.all.page(params[:page]).per(8)
    end
  end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    if params[:check] == "0"
      @orders = Order.all.page(params[:page]).per(10)
    elsif params[:check] && (params[:check] != "0")
      @orders = Order.where(customer_id: params[:check]).page(params[:page]).per(8)
      @notice = "注文履歴のみ表示しています。全ての会員の履歴はページ上部のリンクからご覧ください。"
    else
      @orders = Order.all.page(params[:page]).per(8)
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.order_status == "入金確認"
       @order.order_details.each do |order_detail|
         order_detail.update(production_status: "製作待ち")
       end
    end
      redirect_back(fallback_location: root_path)
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery with: :exception
<<<<<<< HEAD
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number])
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_requied
    redirect_to login_path unless current_user
  end

end
=======
end
>>>>>>> 8affcfd854fc6bc220b8b745150afb732a40f124

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_header.html.erb
<% unless admin_signed_in? %>
  <%# adminサインイン前は会員側のヘッダーを表示 %>
  <%= render "public/shared/header" %>
<% else %>
  <%# adminサインイン済み %>
  <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container">
      <%= link_to image_tag("IMG_logo.JPG",:size =>'180x40'), admin_root_path, class: "navbar-brand" %>


      <span class="badge badge-danger p-2 mr-auto">管理者ページ</span>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "商品一覧",  admin_products_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "会員一覧", admin_customers_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "注文履歴一覧", admin_orders_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container">
      <a class="navbar-brand">
        <% if admin_signed_in? %>
        <%= link_to image_tag("IMG_logo.JPG"), admin_root_path, class: "navbar-brand" %>
        <% else %>
        <%= link_to image_tag("IMG_logo.JPG"), root_path, class: "navbar-brand" %>
        <% end %>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <% if customer_signed_in? %>
          <!--カスタマーがログインしている時-->
            <li class="header-name">
              ようこそ、<%= current_customer.first_name %>さん！
            </li>
            <li><%= link_to "マイページ", customers_path(current_customer), class: "nav-link" %></li>
            <li><%= link_to "商品一覧", products_path, class: "nav-link" %></li>
            <li><%= link_to "カート", cart_products_path, class: "nav-link" %></li>
            <li><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link" %></li>

          <% elsif admin_signed_in? %>
          <!--管理者がログインしている時-->
            <li><%= link_to "商品一覧", admin_products_path, class: "nav-link" %></li>
            <li><%= link_to "会員一覧", admin_customers_path, class: "nav-link" %></li>
            <li><%= link_to "注文履歴一覧", admin_orders_path, class: "nav-link" %></li>
            <li><%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link" %></li>
            <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %></li>

          <% else %>
          <!--ログインしていない時-->
            <li><%= link_to "About", homes_about_path, class: "nav-link" %></li>
            <li><%= link_to "商品一覧", products_path, class: "nav-link" %></li>
            <li><%= link_to "新規登録", new_customer_registration_path, class: "nav-link" %></li>
            <li><%= link_to "ログイン", new_customer_session_path, class: "nav-link" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<<<<<<< HEAD
  <body class="min-vh-100 d-flex flex-column">
    <header class="mb-4">
      <% if controller.class.parent.name == "Admin" %>
        <%# Admin側のヘッダー %>
        <%= render "admins/shared/header" %>
      <% else %>
        <%# Public側のヘッダー %>
        <%= render "public/shared/header" %>
      <% end %>
    </header>
    <main class="flex-grow-1">
      <%= yield %>
    </main>
    <footer class="mt-4">
      <%= render "layouts/footer" %>
    </footer>
  </body>
</html>
=======
  <body>
    <%= yield %>
  </body>
</html>
>>>>>>> 8affcfd854fc6bc220b8b745150afb732a40f124